
package GUI;

import GUI.Login;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import java.text.SimpleDateFormat;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author Carlos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     * @throws java.beans.PropertyVetoException
     */
    public Menu() throws PropertyVetoException {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagem/fundo_menu.png"));
        Image image = icon.getImage();
        Menu = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jPanel2 = new javax.swing.JPanel();
        lblusuario = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cli = new javax.swing.JMenu();
        Estoque = new javax.swing.JMenu();
        Funcionario = new javax.swing.JMenu();
        Produto = new javax.swing.JMenu();
        venda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Descon = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );

        lblusuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblusuario.setText("Usuario");
        lblusuario.setName(""); // NOI18N

        lbldata.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbldata.setText("Data");

        lblhora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblhora.setText("Hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(lbldata)
                .addGap(207, 207, 207)
                .addComponent(lblhora)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldata)
                    .addComponent(lblhora)
                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(489, 30));

        cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/group.png"))); // NOI18N
        cli.setText("Cliente");
        cli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliMouseClicked(evt);
            }
        });
        jMenuBar1.add(cli);

        Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/package.png"))); // NOI18N
        Estoque.setText("Estoque");
        Estoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstoqueMouseClicked(evt);
            }
        });
        jMenuBar1.add(Estoque);

        Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user.png"))); // NOI18N
        Funcionario.setText("Funcionário");
        Funcionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FuncionarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(Funcionario);

        Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cart.png"))); // NOI18N
        Produto.setText("Produto");
        Produto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdutoMouseClicked(evt);
            }
        });
        jMenuBar1.add(Produto);

        venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/basket.png"))); // NOI18N
        venda.setText("Venda");
        venda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setText("Efetuar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        venda.add(jMenuItem1);

        jMenuItem2.setText("Relatório");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        venda.add(jMenuItem2);

        jMenuBar1.add(venda);

        Descon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/door_out.png"))); // NOI18N
        Descon.setText("Desconectar");
        Descon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Descon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesconMouseClicked(evt);
            }
        });
        jMenuBar1.add(Descon);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DesconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesconMouseClicked
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja desconectar?","Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
        dispose();
        Login t = new Login();
        t.setVisible(true);}
        
    }//GEN-LAST:event_DesconMouseClicked

    private void FuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FuncionarioMouseClicked
       funcionario f = new funcionario();
       Menu.add(f);
       f.setVisible(true);
        
    }//GEN-LAST:event_FuncionarioMouseClicked

    private void cliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliMouseClicked
    cliente c = new cliente();
    Menu.add(c);
    c.setVisible(true);
    
    }//GEN-LAST:event_cliMouseClicked

    private void EstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstoqueMouseClicked
       estoque e = new estoque();
        Menu.add(e);
        e.setVisible(true);
        
    }//GEN-LAST:event_EstoqueMouseClicked

    private void ProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutoMouseClicked
        produto p = new produto();
        Menu.add(p);
        p.setVisible(true);
        
    }//GEN-LAST:event_ProdutoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
        Date dataHora = new Date(); 
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHora);
        lblhora.setText(hora);
        
       Date dataHoraAtual = new Date();       
       String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
       lbldata.setText(data);
       
       Timer time = new Timer( 1000, new horaatual());
       time.start();
       
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GUIVendas v = new GUIVendas();
        Menu.add(v);
        v.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Relatorio vc = new Relatorio();
        Menu.add(vc);
        vc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Menu().setVisible(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Descon;
    public static javax.swing.JMenu Estoque;
    public static javax.swing.JMenu Funcionario;
    private javax.swing.JDesktopPane Menu;
    public static javax.swing.JMenu Produto;
    public static javax.swing.JMenu cli;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbldata;
    private javax.swing.JLabel lblhora;
    public static javax.swing.JLabel lblusuario;
    public static javax.swing.JMenu venda;
    // End of variables declaration//GEN-END:variables

    class horaatual implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            Date dataHoraAtual = new Date(); 
            String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);
            lblhora.setText(hora);
        }
    
    
}
    
}

